// Generated by CoffeeScript 2.6.1
(function() {
  var Modules;

  Modules = {
    allmodulesgenmodule: require("./allmodulesgenmodule"),
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    debugmodule: require("./debugmodule"),
    modulesearchmodule: require("./modulesearchmodule"),
    syncprocessmodule: require("./syncprocessmodule"),
    pathhandlermodule: require("./pathhandlermodule"),
    startupmodule: require("./startupmodule"),
    modulesearchmodule: require("./modulesearchmodule"),
    utilmodule: require("./utilmodule")
  };

  module.exports = Modules;

}).call(this);
