// Generated by CoffeeScript 2.6.1
  //###############################################################################
import {
  addModulesToDebug
} from "thingy-debug";

//###############################################################################
addModulesToDebug({});

// allmodulesgenmodule: true
// cliargumentsmodule: true
// configmodule: true
// syncprocessmodule: true
// modulesearchmodule: true
// pathhandlermodule: true
// startupmodule: true
// utilmodule: true
