// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var allmodulesPath, checkProvidedPath, findAllmodulesPath, findSourcePath, log, olog, sourcePath, thingyPath;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("pathhandlermodule"));

import fs from "fs-extra";

import c from 'chalk';

import * as pathModule from "path";

import * as utl from "./utilmodule.js";

//endregion

//#############################################################################
sourcePath = "";

allmodulesPath = "";

thingyPath = "";

//#############################################################################
//region internal functions
findSourcePath = async function() {
  var exists;
  log("findSourcePath");
  sourcePath = pathModule.resolve(thingyPath, "sources/source");
  exists = (await utl.pathIsDir(sourcePath));
  if (!exists) {
    throw new Error("sourcePath: " + sourcePath + " did not exist! The provided path might not be the thingy root.");
  }
  sourcePath = sourcePath;
};

findAllmodulesPath = async function() {
  var exists;
  log("findAllmodulesPath");
  allmodulesPath = pathModule.resolve(sourcePath, "allmodules");
  exists = (await utl.pathIsDir(allmodulesPath));
  if (!exists) {
    await fs.mkdirs(allmodulesPath);
  }
  allmodulesPath = allmodulesPath;
};

checkProvidedPath = async function(providedPath) {
  var exists;
  log("checkProvidedPath");
  if (providedPath) {
    if (!pathModule.isAbsolute(providedPath)) {
      providedPath = pathModule.resolve(process.cwd(), providedPath);
    }
  } else {
    providedPath = process.cwd();
  }
  exists = (await utl.pathIsDir(providedPath));
  if (!exists) {
    throw new Error("Provided path:'" + providedPath + "' does not exist!");
  }
  thingyPath = providedPath;
};

//endregion

//#############################################################################
//region exposed functions
export var checkPaths = async function(providedPath) {
  log("checkPaths");
  log("checking for providedPath: " + providedPath);
  await checkProvidedPath(providedPath);
  log("resulting thingy path is: " + thingyPath);
  await findSourcePath();
  await findAllmodulesPath();
};

export var getCoffeePath = function(module) {
  var pathPostfix;
  log("getCoffeeModulePath");
  pathPostfix = "" + module + "/" + module + ".coffee";
  return pathModule.resolve(sourcePath, pathPostfix);
};

export var getStylePath = function(module) {
  var pathPostfix;
  log("getStylePath");
  pathPostfix = "" + module + "/styles.styl";
  return pathModule.resolve(sourcePath, pathPostfix);
};

export var getPackageJsonPath = function() {
  log("getPackageJsonPath");
  return pathModule.resolve(thingyPath, "package.json");
};

//#############################################################################
export var getSourcePath = function() {
  return sourcePath;
};

export var getAllmodulesPath = function() {
  return allmodulesPath;
};

export var getThingyPath = function() {
  return thingyPath;
};

//endregion
