// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog, successMessage;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("syncprocessmodule"));

import * as c from 'chalk';

import * as pathHandler from "./pathhandermodule.js";

import * as moduleSearch from "./modulesearchmodule.js";

import * as allmodulesgen from "./allmodulesgenmodule.js";

//endregion

//#############################################################################
successMessage = function(arg) {
  return console.log(c.green(arg));
};

//#############################################################################
export var execute = async function(path) {
  var modules;
  log("execute");
  await pathHandler.checkPaths(path);
  modules = (await moduleSearch.searchModules());
  log("found modules\n" + JSON.stringify(modules, null, 4));
  await allmodulesgen.generate(modules);
  return true;
};
