// Generated by CoffeeScript 2.6.1
(function() {
  var allmodulesgen, c, log, moduleSearch, pathHandler, successMessage, syncprocessmodule;

  syncprocessmodule = {
    name: "syncprocessmodule"
  };

  //region node_modules
  c = require('chalk');

  //endregion

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["syncprocessmodule"] != null) {
      console.log("[syncprocessmodule]: " + arg);
    }
  };

  //region internal variables
  successMessage = function(arg) {
    return console.log(c.green(arg));
  };

  pathHandler = null;

  moduleSearch = null;

  allmodulesgen = null;

  //endregion

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  syncprocessmodule.initialize = function() {
    log("syncprocessmodule.initialize");
    pathHandler = allModules.pathhandlermodule;
    moduleSearch = allModules.modulesearchmodule;
    return allmodulesgen = allModules.allmodulesgenmodule;
  };

  //region internal functions
  //endregion

  //region exposed functions
  syncprocessmodule.execute = async function(path, style) {
    var modules;
    log("syncprocessmodule.execute");
    await pathHandler.checkPaths(path);
    modules = (await moduleSearch.searchModules());
    log("found modules\n" + JSON.stringify(modules, null, 4));
    await allmodulesgen.generate(modules, style);
    return true;
  };

  
  //endregion
  module.exports = syncprocessmodule;

}).call(this);
