// Generated by CoffeeScript 2.6.1
(function() {
  var fs, log, utilmodule;

  utilmodule = {
    name: "utilmodule"
  };

  //region noode_modules
  fs = require("fs-extra");

  //endregion

  //log Switch
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["utilmodule"] != null) {
      console.log("[utilmodule]: " + arg);
    }
  };

  //region internal variables
  //endregion

  //region exposed variables
  //endregion

  //#initialization function  -> is automatically being called!  ONLY RELY ON DOM AND VARIABLES!! NO PLUGINS NO OHTER INITIALIZATIONS!!
  utilmodule.initialize = function() {
    return log("utilmodule.initialize");
  };

  //region internal functions
  //endregion

  //region exposed functions
  utilmodule.pathIsDir = async function(path) {
    var err, stats;
    try {
      stats = (await fs.lstat(path));
      return stats.isDirectory();
    } catch (error) {
      err = error;
      // console.log(c.red(err.message))
      return false;
    }
  };

  utilmodule.pathExists = async function(path) {
    var err;
    try {
      await fs.lstat(path);
      return true;
    } catch (error) {
      err = error;
      // console.log(c.red(err.message))
      return false;
    }
  };

  //endregion
  module.exports = utilmodule;

}).call(this);
