// Generated by CoffeeScript 2.6.1
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("utilmodule"));

import fs from "fs-extra";

//#############################################################################
//region exposed functions
export var pathIsDir = async function(path) {
  var err, stats;
  try {
    stats = (await fs.lstat(path));
    return stats.isDirectory();
  } catch (error) {
    err = error;
    // console.log(c.red(err.message))
    return false;
  }
};

export var pathExists = async function(path) {
  var err;
  try {
    await fs.lstat(path);
    return true;
  } catch (error) {
    err = error;
    // console.log(c.red(err.message))
    return false;
  }
};

//endregion
